/**
 * STRATEGY EVALUATION ENGINE
 * 
 * Takes an Abstract Syntax Tree (AST) generated by the parser and evaluates it daily
 * against the current market day's price indicators and the user's portfolio context.
 * 
 * For beginners:
 * - This engine behaves like a mini CPU/Interpreter: it reads each statement,
 *   performs calculations (addition, comparisons), checks conditional branches (if/else),
 *   and executes special instructions (like buy and sell calls).
 * - Trading function calls (like buy, sell) do not execute immediately. Instead,
 *   they are pushed onto an "orders" queue which the Backtest Engine executes on the NEXT morning open.
 */
export class StrategyEngine {
  constructor(ast, portfolioState, symbol) {
    this.ast = ast;
    this.portfolio = portfolioState;
    this.symbol = symbol;
    this.orders = []; // Orders generated during evaluation on this simulated day
    this.vars = {};   // Active execution environment variables (closes, indicators, cash, etc.)
  }

  /**
   * Run strategy for one simulated trading day.
   * Returns array of generated orders to execute on tomorrow's market open.
   * 
   * @param {Object} context - Today's market variables and indicators
   * @returns {Array} List of pending orders
   */
  evaluate(context) {
    this.vars = { ...context };
    this.orders = [];
    if (this.ast?.body) {
      for (const stmt of this.ast.body) {
        this.executeStatement(stmt);
      }
    }
    return this.orders;
  }

  /**
   * Router to execute individual statement node types.
   */
  executeStatement(node) {
    if (!node) return;
    switch (node.type) {
      case 'IfStatement':
        // Evaluate the boolean condition and execute correct branch block
        if (this.evaluateExpression(node.condition)) {
          this.executeBlock(node.consequent);
        } else if (node.alternate) {
          this.executeBlock(node.alternate);
        }
        break;
      case 'ExpressionStatement':
        this.evaluateExpression(node.expression);
        break;
      case 'BlockStatement':
        this.executeBlock(node);
        break;
      default:
        break;
    }
  }

  /**
   * Executes list of statements inside block braces.
   */
  executeBlock(block) {
    if (!block?.body) return;
    for (const stmt of block.body) {
      this.executeStatement(stmt);
    }
  }

  /**
   * AST INTERPRETER (RECURSIVE EVALUATION)
   * 
   * For Beginners:
   * What is an Interpreter?
   * An interpreter reads code represented as a structure (our AST) and executes it step-by-step
   * on the fly. This method `evaluateExpression` is the core of our interpreter.
   * 
   * How recursion works here:
   * If the engine sees a nested sum like `(open + close) > sma20`, the AST structure is:
   *    BinaryExpression(operator: '>', left: BinaryExpression(operator: '+', left: 'open', right: 'close'), right: 'sma20')
   * 
   * 1. It calls `evaluateExpression` on the main '>' BinaryExpression.
   * 2. This splits the work, recursively calling `evaluateExpression` on the left side ('open + close') and the right side ('sma20').
   * 3. The left side ('open + close') is evaluated by recursively adding 'open' value and 'close' value.
   * 4. Once the leaves (identifiers/literals) return numbers, they bubble back up to solve the main inequality.
   */
  evaluateExpression(node) {
    if (!node) return 0;

    switch (node.type) {
      case 'Literal':
        return node.value; // E.g. returns raw number 30
      case 'Identifier':
        return this.vars[node.name] ?? 0; // Looks up variable name in daily context (e.g. 'rsi' -> 45)
      case 'UnaryExpression':
        // Evaluates negative signs: -sma20 -> -1 * sma20 value
        return node.operator === '-' ? -this.evaluateExpression(node.argument) : this.evaluateExpression(node.argument);
      case 'BinaryExpression':
        // Evaluates standard math and conditional comparisons between two variables
        return this.applyBinary(node.operator, node.left, node.right);
      case 'CallExpression':
        // Executes trading functions
        return this.executeCall(node);
      default:
        return 0;
    }
  }

  /**
   * Applies math or logic operators between left and right expressions.
   */
  applyBinary(op, left, right) {
    const l = this.evaluateExpression(left);
    const r = this.evaluateExpression(right);
    switch (op) {
      case '+': return l + r;
      case '-': return l - r;
      case '*': return l * r;
      case '/': return r !== 0 ? l / r : 0; // Guard against division-by-zero crashes
      case '>': return l > r;
      case '<': return l < r;
      case '>=': return l >= r;
      case '<=': return l <= r;
      case '==': return l === r;
      case '!=': return l !== r;
      case '&&': return l && r;
      case '||': return l || r;
      default: return 0;
    }
  }

  /**
   * Handles trading function calls.
   * Maps functions to order requests which queue for execution on the next day's open.
   */
  executeCall(node) {
    const { callee, arguments: args } = node;
    const pos = this.portfolio.positions[this.symbol] || { shares: 0, avgPrice: 0 };

    switch (callee) {
      case 'buy': {
        const qty = Math.floor(this.evaluateExpression(args[0]));
        if (qty > 0) {
          this.orders.push({ action: 'BUY', symbol: this.symbol, quantity: qty });
        }
        return qty;
      }
      case 'sell': {
        const qty = Math.floor(this.evaluateExpression(args[0]));
        const sellQty = Math.min(qty, pos.shares); // Cannot sell more shares than we currently own
        if (sellQty > 0) {
          this.orders.push({ action: 'SELL', symbol: this.symbol, quantity: sellQty });
        }
        return sellQty;
      }
      case 'buy_all':
        // Queues an order to spend all cash on this stock
        this.orders.push({ action: 'BUY_ALL', symbol: this.symbol });
        return 1;
      case 'sell_all':
        // Queues an order to sell all owned shares of this stock
        if (pos.shares > 0) {
          this.orders.push({ action: 'SELL_ALL', symbol: this.symbol });
        }
        return pos.shares;
      case 'shares_owned':
        return pos.shares;
      case 'current_cash':
        return this.portfolio.cash;
      case 'portfolio_value':
        return this.portfolio.totalValue;
      default:
        return 0;
    }
  }
}
