/**
 * BACKTEST DETAILED REPORT MODEL SCHEMAS (Backtest.js)
 * 
 * For Beginners:
 * This database schema stores the complete logs and daily metrics generated by a backtest simulation run.
 * Because a single backtest creates a lot of structured data (e.g. daily equity curve points, complete list
 * of trades, daily stock prices), we store these as arrays and object types inside a single database document.
 * 
 * Concepts Covered:
 * 1. Mongoose Array and Object types:
 *    - `trades: { type: Array }`: A list containing all BUY/SELL transaction details.
 *    - `priceData: { type: Object }`: A nested dictionary containing daily OHLC prices mapped by stock ticker key.
 * 2. Compounded and Volatility Metrics:
 *    Stores CAGR, Sharpe ratio, Sortino ratio, Max Drawdown, and profit factor to enable analytics plotting on the frontend.
 */

import mongoose from 'mongoose';
import { createModelProxy } from '../utils/dbProxy.js';

const backtestSchema = new mongoose.Schema({
  backtestId: { type: String, required: true, unique: true },
  userId: { type: String, required: true, index: true }, // Index accelerates user history retrieval queries
  userName: { type: String, required: true },
  strategyId: { type: String, default: null },
  strategyName: { type: String, required: true },
  stocks: [{ type: String }],
  startDate: { type: String, required: true },
  endDate: { type: String, required: true },
  
  // Capital structures
  initialCapital: { type: Number, required: true },
  finalCapital: { type: Number, required: true },
  netProfit: { type: Number, default: 0 },
  returnPercent: { type: Number, required: true },
  
  // Performance and Volatility metrics
  cagr: { type: Number, default: 0 },
  sharpeRatio: { type: Number, default: 0 },
  sortinoRatio: { type: Number, default: 0 },
  drawdown: { type: Number, default: 0 },
  profitFactor: { type: Number, default: 0 },
  
  // Win / Loss statistics
  winRate: { type: Number, default: 0 },
  avgTrade: { type: Number, default: 0 },
  bestTrade: { type: Number, default: 0 },
  worstTrade: { type: Number, default: 0 },
  totalTrades: { type: Number, default: 0 },
  avgHoldingPeriod: { type: Number, default: 0 },
  
  // Detailed time-series logs
  trades: { type: Array, default: [] },          // List of individual transactions
  equityCurve: { type: Array, default: [] },      // Daily portfolio value curve
  drawdownCurve: { type: Array, default: [] },    // Daily drawdown drawdown curve
  monthlyReturns: { type: Array, default: [] },   // Aggregated monthly performance percentages
  portfolioGrowth: { type: Array, default: [] },  // Replicated duplicate curve matching equity curve
  priceData: { type: Object, default: {} },       // Nested candlestick coordinates mapped by stock symbol key
  
  createdAt: { type: Date, default: Date.now },
});

export default createModelProxy(mongoose.model('Backtest', backtestSchema), 'backtests', 'backtestId');
