/**
 * AI COMPANION CONTROLLER (aiController.js)
 * 
 * For Beginners:
 * This controller intercepts frontend code requests and routes them to our AI services.
 * 
 * Flow of AI calls:
 * 1. Receive the code or user prompt.
 * 2. Forward parameters to the `aiService.js` wrapper which queries Google's Gemini models.
 * 3. Validate generated/fixed code. If the AI returns code, we run it through `parseStrategy(code)`
 *    to make sure it doesn't contain syntax errors, and pass the code and validation status back to the client.
 * 
 * Concepts Covered:
 * - Parsing generated assets: Checking generated outputs against compiler parsers to guarantee correct syntax.
 */

import { generateStrategy } from '../services/aiService.js';
import { parseStrategy } from '../parser/parser.js';

/**
 * generate - Creates strategy templates from user descriptions.
 * Route: POST /api/ai/generate (Authenticated)
 */
export const generate = async (req, res) => {
  try {
    const { prompt } = req.body;
    if (!prompt?.trim()) return res.status(400).json({ error: 'Prompt is required' });

    // 1. Ask Gemini to write C++ code matching the user prompt
    const code = await generateStrategy(prompt);
    
    // 2. Validate the code generated by the AI to make sure it matches our custom DSL grammar rules
    const validation = parseStrategy(code);
    
    res.json({ code, validation });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};
